#!/bin/bash

anynode="config.json"
hostflyte="config2.json"

a=$(ps -aux | grep nobody | grep shadowsocks)
b=${a##*/}

if [ $b = $anynode ]
then
    echo -e "\033[32m The server now is anynode. \033[0m"
elif [ $b = $hostflyte ]
then
    echo -e "\033[32m The server now is hostflyte. \033[0m"
else
    echo -e "\033[31m Shadowsocks seems not running! \033[0m"
fi

echo -e "\033[35m Please select your server: \033[0m"
echo -e "\033[35m 1.anynode  2.hostflyte  0.restart current server \033[0m"
read -p "[Default:0] " num
if [ -z $num ]; then num=0; fi
case $num in
1)
    sudo systemctl stop shadowsocks-libev@${b%.*}
    sudo systemctl start shadowsocks-libev@${anynode%.*}
    echo -e "\033[32m Change server to anynode successfully! \033[0m"
    ;;
2)
    sudo systemctl stop shadowsocks-libev@${b%.*}
    sudo systemctl start shadowsocks-libev@${hostflyte%.*}
    echo -e "\033[32m Change server to hostflyte successfully! \033[0m"
    ;;
0)
    sudo systemctl restart shadowsocks-libev@${b%.*}
    echo -e "\033[32m Restart successfully! \033[0m"
    ;;
*)
    echo -e "\033[34m Nothing to do! \033[0m"
esac
